onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Digital_Watch_tb/clk
add wave -noupdate /Digital_Watch_tb/Set_Time_Alarm/tens_hours_in
add wave -noupdate /Digital_Watch_tb/Set_Time_Alarm/units_hours_in
add wave -noupdate /Digital_Watch_tb/Set_Time_Alarm/tens_minutes_in
add wave -noupdate /Digital_Watch_tb/Set_Time_Alarm/units_minutes_in
add wave -noupdate /Digital_Watch_tb/Set_Time_Alarm/i
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/Normal
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/SetTime
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/SetAlarm
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/StopWatch
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/clk
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/rst
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/mode
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/set
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/setting_done
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/split_mode
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/normal_mode_en
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/setting_mode_en
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/alarm_mode_en
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/stopwatch_mode_en
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/current_state
add wave -noupdate /Digital_Watch_tb/uut/fsm_inst/next_state
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/mode
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/set
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/normal_mode_en
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_mode_en
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/setting_mode_en
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/setting_done
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/tens_hours_out
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/units_hours_out
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/tens_minutes_out
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/units_minutes_out
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_sound
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/tens_hours
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/units_hours
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/tens_minutes
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/units_minutes
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/setting_digit
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/sec_count
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_hours
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_minutes
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_counter
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_active
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/set_hours
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/set_minutes
add wave -noupdate /Digital_Watch_tb/uut/clock_inst/alarm_done
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/clk
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/rst
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/mode
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/set
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/stopwatch_mode_en
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/min_out
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/sec_out
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/split_mode
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/stopwatch_mode
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/split_captured
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/sec_count
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/min_count
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/sec_count_split
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/min_count_split
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/Elapsed_state
add wave -noupdate /Digital_Watch_tb/uut/stopwatch_inst/Split_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {333999 ms} 0}
quietly wave cursor active 1
configure wave -namecolwidth 321
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {667515 ms} {701407 ms}
